### PR TITLE
Fix: rules splitting regexp.

### LINKED ISSUE #29: Rule with tab causes erroneous appending to previous one.
Tab character in rule causes appending to previous one, even if not at start.
(And "^|  #" is treated like comment line. I have patched it, sending pull request).

### PR DESCRIPTION
**Pull request by peter-kolenic**
- \t caused continuation, even if not at start
- fix of comment parsing.
  Fixes https://github.com/hafriedlander/php-peg/issues/29

### CODE REVIEW

**Comment by hafriedlander** [comment]
Thanks, good catch

**Comment by hafriedlander** [comment]
Incidentally, if possible, when fixing an issue it'd be good if the PR came with a test that failed before & passed after the fix.

**Comment by peter-kolenic** [comment]
1. Thank You for this project.
2. test for tab is here, if:
   https://github.com/peter-kolenic/php-peg/commit/f932b5289772cd33b8744d2cfc1e0e9e671d148a
   Is it OK to add it to base syntax test, or should i make new function or file for corner cases ? 
   (the other bug seems too obscure to me to be added there, so i wait for Your reply).

**Comment by hafriedlander** [comment]
Unfortunately the test coverage isn't very good at the moment - normally you'd add it to the existing tests for tabs, but there aren't any, it's all in that one test :).

Other than using `Quux` for consistency instead of tabtest (as per http://en.wikipedia.org/wiki/Metasyntactic_variable#English) that test looks fine.

**Comment by peter-kolenic** [comment]
OK, :-), https://github.com/peter-kolenic/php-peg/commit/a534bf62f74c8e776b9b241c277480b457d97072

should i issue new PR ?

**Comment by hafriedlander** [comment]
Yes please.

**Pull request merged**
